### ISSUE TITLE
Make sure @mlg slot is of class MLG before filtering

### ISSUE THREAD

**Issue by zkamvar** [JonahBrooks/poppr#10]
[In these lines in the function bruvo.msn](https://github.com/JonahBrooks/poppr/blob/0faa5e04c8e6c807219beaa50dabd1e5038972c6/R/bruvo.r#L480-L491) there are two problems:
- The filtering assumes that the mlg slot is of class MLG. This must be forced. Do it like so before line 482:

``` r
pop@mlg <- new("MLG", pop@mlg)
```
- Line 491 assumes that "contracted" mlgs are the ones to use for the MSN. Change this back to the normal method and set the @visible slot to "contracted" within the if statement:

``` r
pop@mlg@visible <- "contracted"
```

**Comment by zkamvar** [comment]
This issue requires immediate attention.

**Comment by JonahBrooks** [comment]
This should be fixed in commit d1646caf5a413d05c3de154c2084fd081e41b2eb

Note that this fix will change when issue #5 is resolved, as a number of lines from bruvo.msn will move into mlg.filter itself. For now this hopefully resolves the issues mentioned here.

**Comment by JonahBrooks** [comment]
Commit 1884506d8dad30e7b43e6e0d7f3c39352b361073 extends this fix to poppr.msn and singlepop_msn

**Comment by zkamvar** [comment]
I declare this issue fixed!
