### ISSUE TITLE
Add function to tell user if poppr is installed with parallel support

### ISSUE THREAD

**Issue by zkamvar** [JonahBrooks/poppr#9]
It can be a simple R function that calls a C function with an `#ifdef` for openmp and returns TRUE or FALSE.

**Comment by JonahBrooks** [comment]
check_openMP_support() has been added in commit 457d7c58fd29c0defd0c3fdc73cc4a9d95a24205 

I'm not sure where we ultimately want this code to reside, so I made a new C file and put the R code in bitwise.r. We can move it around easily enough if there is a better place for it.

**Comment by zkamvar** [comment]
Suggestion for changing the function name to `poppr_has_parallel()`. This will syntactically be easier for users to understand e.g.

``` r
if (poppr_has_parallel()){
    # Do something cool
} else {
    # Do something equally as cool, but not as fast
}
```

**Comment by JonahBrooks** [comment]
Good point. That's much easier to understand. Renamed as such in commit 105a615ee04f62eea343ad52decfcf5a5a499705
